services:
  database:
    image: postgres:18-alpine
    container_name: luminai_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    # SECURITY: Port removed - database only accessible within Docker network
    # External access must go through application container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - luminai_network

  app:
    build: ./app
    container_name: luminai_app
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      APP_TIMEZONE: ${APP_TIMEZONE:-UTC}
      FRANKENPHP_NUM_THREADS: ${FRANKENPHP_NUM_THREADS}
      SESSION_COOKIE_DOMAIN: ${SESSION_COOKIE_DOMAIN}
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - luminai_network

  messenger_worker:
    build: ./app
    container_name: luminai_messenger_worker
    command: php bin/console messenger:consume async --limit=100 --memory-limit=256M --time-limit=3600
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      APP_TIMEZONE: ${APP_TIMEZONE:-UTC}
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - luminai_network

  redis:
    image: redis:7-alpine
    container_name: luminai_redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru --bind 0.0.0.0 --protected-mode yes
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    # SECURITY: Port removed - Redis only accessible within Docker network
    # External access must go through application container
    # Password authentication required (see REDIS_PASSWORD in .env)
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - luminai_network

  nginx:
    image: nginx:1.27-alpine
    container_name: luminai_nginx
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - luminai_network

volumes:
  postgres_data:
  redis_data:

networks:
  luminai_network:
    driver: bridge