# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Video storage paths
    app.videos.originals_path: '%kernel.project_dir%/var/videos/originals'
    app.videos.hls_path: '%kernel.project_dir%/var/videos/hls'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Generator Services - all need $projectDir parameter
    App\Service\Generator\GeneratorOrchestrator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Entity\EntityGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\ApiPlatform\ApiPlatformGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Repository\RepositoryGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Controller\ControllerGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Voter\VoterGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Form\FormGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Template\TemplateGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Navigation\NavigationGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Translation\TranslationGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Test\EntityTestGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Test\RepositoryTestGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Test\ControllerTestGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\Generator\Test\VoterTestGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'
