<?php

declare(strict_types=1);

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Entity\Agent;
use App\Dto\AgentInputDto;
use App\Service\Utils;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Uid\Uuid;
use App\Entity\Organization;
use App\Entity\TreeFlow;
use App\Entity\User;
use App\Entity\AgentType;
use App\Entity\Talk;

/**
 * Agent State Processor
 *
 * Handles Input DTO -> Entity transformation for POST, PUT, PATCH operations
 * with support for nested object creation and updates.
 *
 * This file is ALWAYS regenerated. DO NOT edit.
 * For custom processing logic, use Event Subscribers.
 *
 * @generated by Genmax Code Generator
 */
class AgentProcessor implements ProcessorInterface
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        #[Autowire(service: 'App\MultiTenant\TenantEntityProcessor')]
        private readonly ProcessorInterface $persistProcessor
    ) {}

    /**
     * Normalize property name for matching (removes underscores, lowercase)
     * Uses centralized Utils methods instead of manual string manipulation
     */
    private function normalizePropertyName(string $property): string
    {
        // Convert to camelCase (handles snake_case, etc.) then lowercase
        return strtolower(Utils::toCamelCase($property));
    }

    /**
     * Extract property name from method name (e.g., 'addItem' -> 'item')
     */
    private function extractPropertyFromMethod(string $methodName, string $prefix): string
    {
        // Remove prefix (e.g., 'add', 'set') and convert to lowercase
        return strtolower(substr($methodName, strlen($prefix)));
    }

    /**
     * @param AgentInputDto $data
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): Agent
    {
        if (!$data instanceof AgentInputDto) {
            throw new BadRequestHttpException('Invalid input data type');
        }

        // Determine if this is a create or update operation
        $entity = null;
        $isUpdate = isset($uriVariables['id']);
        $isPatch = $operation->getMethod() === 'PATCH';

        if ($isUpdate) {
            $entity = $this->entityManager->getRepository(Agent::class)->find($uriVariables['id']);
            if (!$entity) {
                throw new BadRequestHttpException('Agent not found');
            }
        }

        if (!$entity) {
            $entity = new Agent();
        }

        // Get original request data to check which fields were actually sent (for PATCH)
        $requestData = $context['request']->toArray() ?? [];

        // Map scalar properties from DTO to Entity
        // whatsappInstanceName
        if (!$isPatch || array_key_exists('whatsappInstanceName', $requestData)) {
            $entity->setWhatsappInstanceName($data->whatsappInstanceName);
        }
        // whatsappPhone
        if (!$isPatch || array_key_exists('whatsappPhone', $requestData)) {
            $entity->setWhatsappPhone($data->whatsappPhone);
        }
        // whatsappServerUrl
        if (!$isPatch || array_key_exists('whatsappServerUrl', $requestData)) {
            $entity->setWhatsappServerUrl($data->whatsappServerUrl);
        }
        // whatsappApiKey
        if (!$isPatch || array_key_exists('whatsappApiKey', $requestData)) {
            $entity->setWhatsappApiKey($data->whatsappApiKey);
        }
        // whatsappActive
        if (!$isPatch || array_key_exists('whatsappActive', $requestData)) {
            $entity->setWhatsappActive($data->whatsappActive);
        }
        // whatsappStatus
        if (!$isPatch || array_key_exists('whatsappStatus', $requestData)) {
            $entity->setWhatsappStatus($data->whatsappStatus);
        }
        // whatsappWebhookToken
        if (!$isPatch || array_key_exists('whatsappWebhookToken', $requestData)) {
            $entity->setWhatsappWebhookToken($data->whatsappWebhookToken);
        }
        // whatsappLastConnectedAt
        if (!$isPatch || array_key_exists('whatsappLastConnectedAt', $requestData)) {
            $entity->setWhatsappLastConnectedAt($data->whatsappLastConnectedAt);
        }
        // whatsappMetadata
        if (!$isPatch || array_key_exists('whatsappMetadata', $requestData)) {
            $entity->setWhatsappMetadata($data->whatsappMetadata);
        }
        // name
        if (!$isPatch || array_key_exists('name', $requestData)) {
            $entity->setName($data->name);
        }
        // phone
        if (!$isPatch || array_key_exists('phone', $requestData)) {
            $entity->setPhone($data->phone);
        }
        // title
        if (!$isPatch || array_key_exists('title', $requestData)) {
            $entity->setTitle($data->title);
        }
        // active
        if (!$isPatch || array_key_exists('active', $requestData)) {
            $entity->setActive($data->active);
        }
        // available
        if (!$isPatch || array_key_exists('available', $requestData)) {
            $entity->setAvailable($data->available);
        }
        // territory
        if (!$isPatch || array_key_exists('territory', $requestData)) {
            $entity->setTerritory($data->territory);
        }
        // quota
        if (!$isPatch || array_key_exists('quota', $requestData)) {
            $entity->setQuota($data->quota);
        }
        // commissionRate
        if (!$isPatch || array_key_exists('commissionRate', $requestData)) {
            $entity->setCommissionRate($data->commissionRate);
        }
        // startDate
        if (!$isPatch || array_key_exists('startDate', $requestData)) {
            $entity->setStartDate($data->startDate);
        }
        // endDate
        if (!$isPatch || array_key_exists('endDate', $requestData)) {
            $entity->setEndDate($data->endDate);
        }
        // specialization
        if (!$isPatch || array_key_exists('specialization', $requestData)) {
            $entity->setSpecialization($data->specialization);
        }
        // languages
        if (!$isPatch || array_key_exists('languages', $requestData)) {
            $entity->setLanguages($data->languages);
        }
        // certifications
        if (!$isPatch || array_key_exists('certifications', $requestData)) {
            $entity->setCertifications($data->certifications);
        }
        // totalSales
        if (!$isPatch || array_key_exists('totalSales', $requestData)) {
            $entity->setTotalSales($data->totalSales);
        }
        // currentMonthSales
        if (!$isPatch || array_key_exists('currentMonthSales', $requestData)) {
            $entity->setCurrentMonthSales($data->currentMonthSales);
        }
        // conversionRate
        if (!$isPatch || array_key_exists('conversionRate', $requestData)) {
            $entity->setConversionRate($data->conversionRate);
        }
        // customerSatisfactionScore
        if (!$isPatch || array_key_exists('customerSatisfactionScore', $requestData)) {
            $entity->setCustomerSatisfactionScore($data->customerSatisfactionScore);
        }
        // maxConcurrentCustomers
        if (!$isPatch || array_key_exists('maxConcurrentCustomers', $requestData)) {
            $entity->setMaxConcurrentCustomers($data->maxConcurrentCustomers);
        }
        // currentCustomerCount
        if (!$isPatch || array_key_exists('currentCustomerCount', $requestData)) {
            $entity->setCurrentCustomerCount($data->currentCustomerCount);
        }
        // averageResponseTime
        if (!$isPatch || array_key_exists('averageResponseTime', $requestData)) {
            $entity->setAverageResponseTime($data->averageResponseTime);
        }
        // skills
        if (!$isPatch || array_key_exists('skills', $requestData)) {
            $entity->setSkills($data->skills);
        }
        // prompt
        if (!$isPatch || array_key_exists('prompt', $requestData)) {
            $entity->setPrompt($data->prompt);
        }

        // Map relationship properties
        // organization: ManyToOne
        // organization is auto-assigned by TenantEntityProcessor if not provided
        if (!$isPatch || array_key_exists('organization', $requestData)) {
            if ($data->organization !== null) {
                if (is_string($data->organization)) {
                    // IRI format: "/api/organizatia/{id}"
                    $organizationId = $this->extractIdFromIri($data->organization);
                    $organization = $this->entityManager->getRepository(Organization::class)->find($organizationId);
                    if (!$organization) {
                        throw new BadRequestHttpException('Organization not found: ' . $organizationId);
                    }
                    $entity->setOrganization($organization);
                } else {
                    // Nested object creation (if supported)
                    throw new BadRequestHttpException('Nested organization creation not supported. Use IRI format.');
                }
            }
        }

        // treeFlow: ManyToOne
        if (!$isPatch || array_key_exists('treeFlow', $requestData)) {
            if ($data->treeFlow !== null) {
                if (is_string($data->treeFlow)) {
                    // IRI format: "/api/tree_flows/{id}"
                    $treeFlowId = $this->extractIdFromIri($data->treeFlow);
                    $treeFlow = $this->entityManager->getRepository(TreeFlow::class)->find($treeFlowId);
                    if (!$treeFlow) {
                        throw new BadRequestHttpException('TreeFlow not found: ' . $treeFlowId);
                    }
                    $entity->setTreeFlow($treeFlow);
                } else {
                    // Nested object creation (if supported)
                    throw new BadRequestHttpException('Nested treeFlow creation not supported. Use IRI format.');
                }
            }
        }

        // user: ManyToOne
        if (!$isPatch || array_key_exists('user', $requestData)) {
            if ($data->user !== null) {
                if (is_string($data->user)) {
                    // IRI format: "/api/users/{id}"
                    $userId = $this->extractIdFromIri($data->user);
                    $user = $this->entityManager->getRepository(User::class)->find($userId);
                    if (!$user) {
                        throw new BadRequestHttpException('User not found: ' . $userId);
                    }
                    $entity->setUser($user);
                } else {
                    // Nested object creation (if supported)
                    throw new BadRequestHttpException('Nested user creation not supported. Use IRI format.');
                }
            }
        }

        // agentType: ManyToOne
        if (!$isPatch || array_key_exists('agentType', $requestData)) {
            if ($data->agentType !== null) {
                if (is_string($data->agentType)) {
                    // IRI format: "/api/agent_types/{id}"
                    $agentTypeId = $this->extractIdFromIri($data->agentType);
                    $agentType = $this->entityManager->getRepository(AgentType::class)->find($agentTypeId);
                    if (!$agentType) {
                        throw new BadRequestHttpException('AgentType not found: ' . $agentTypeId);
                    }
                    $entity->setAgentType($agentType);
                } else {
                    // Nested object creation (if supported)
                    throw new BadRequestHttpException('Nested agentType creation not supported. Use IRI format.');
                }
            }
        }

        // Persist and flush
        return $this->persistProcessor->process($entity, $operation, $uriVariables, $context);
    }

    /**
     * Extract UUID from IRI format
     */
    private function extractIdFromIri(string $iri): Uuid
    {
        $parts = explode('/', $iri);
        $id = end($parts);

        if (!Uuid::isValid($id)) {
            throw new BadRequestHttpException('Invalid UUID in IRI: ' . $iri);
        }

        return Uuid::fromString($id);
    }

    /**
     * Map array data to entity properties using setters
     * Handles nested collections recursively
     *
     * @param array $data Associative array of property => value
     * @param object $entity Target entity instance
     */
    private function mapArrayToEntity(array $data, object $entity): void
    {
        foreach ($data as $property => $value) {
            // Skip special keys like @id, @type, @context
            if (str_starts_with($property, '@')) {
                continue;
            }

            // Handle nested collections using reflection to find adder methods
            if (is_array($value) && !empty($value) && isset($value[0]) && is_array($value[0])) {
                // Find adder method using reflection - scan all methods starting with 'add'
                $reflectionClass = new \ReflectionClass($entity);
                foreach ($reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC) as $method) {
                    if (!str_starts_with($method->getName(), 'add')) {
                        continue;
                    }

                    // Check if this might be the right adder based on property name similarity
                    $normalizedProperty = $this->normalizePropertyName($property);
                    $extractedFromMethod = $this->extractPropertyFromMethod($method->getName(), 'add');

                    // Try to match: property name should be similar to method's entity name
                    // e.g., 'items' matches 'addItem', 'user_items' matches 'addUserItem'
                    if (!str_contains($normalizedProperty, $extractedFromMethod) &&
                        !str_contains($extractedFromMethod, $normalizedProperty)) {
                        continue;
                    }

                    $parameters = $method->getParameters();
                    if (count($parameters) > 0) {
                        $paramType = $parameters[0]->getType();
                        if ($paramType && $paramType instanceof \ReflectionNamedType) {
                            $className = $paramType->getName();
                            if (class_exists($className)) {
                                $addMethod = $method->getName();
                                $setParentMethods = array_filter(
                                    $reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC),
                                    fn($m) => str_starts_with($m->getName(), 'set')
                                );

                                foreach ($value as $itemData) {
                                    $item = new $className();
                                    $this->mapArrayToEntity($itemData, $item);

                                    // Try to set parent relationship using reflection
                                    $itemReflection = new \ReflectionClass($item);
                                    foreach ($itemReflection->getMethods(\ReflectionMethod::IS_PUBLIC) as $itemMethod) {
                                        if (str_starts_with($itemMethod->getName(), 'set')) {
                                            $params = $itemMethod->getParameters();
                                            if (count($params) > 0) {
                                                $paramType = $params[0]->getType();
                                                if ($paramType instanceof \ReflectionNamedType &&
                                                    $paramType->getName() === get_class($entity)) {
                                                    $item->{$itemMethod->getName()}($entity);
                                                    break;
                                                }
                                            }
                                        }
                                    }

                                    $entity->$addMethod($item);
                                    $this->entityManager->persist($item);
                                }
                                continue 2; // Skip to next property
                            }
                        }
                    }
                }
            }

            // Find setter method using reflection - no string manipulation guessing
            $reflectionClass = new \ReflectionClass($entity);
            $setter = null;
            foreach ($reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC) as $method) {
                if (!str_starts_with($method->getName(), 'set')) {
                    continue;
                }

                // Check if method name matches property (case-insensitive, normalized matching)
                $extractedFromMethod = $this->extractPropertyFromMethod($method->getName(), 'set');
                $normalizedProperty = $this->normalizePropertyName($property);

                if ($extractedFromMethod === $normalizedProperty) {
                    $setter = $method->getName();
                    break;
                }
            }

            if (method_exists($entity, $setter)) {
                // Handle different value types
                if ($value instanceof \DateTimeInterface || $value === null || is_scalar($value)) {
                    $entity->$setter($value);
                } elseif (is_array($value) && !empty($value)) {
                    // Handle JSON arrays (like metadata, tags) - not entity collections
                    $entity->$setter($value);
                } elseif (is_string($value) && str_starts_with($value, '/api/') && $setter) {
                    // Handle IRI references - use reflection to determine expected type
                    try {
                        $refId = $this->extractIdFromIri($value);

                        // Use reflection to get the expected parameter type for the setter
                        $reflectionMethod = new \ReflectionMethod($entity, $setter);
                        $parameters = $reflectionMethod->getParameters();

                        if (count($parameters) > 0) {
                            $paramType = $parameters[0]->getType();
                            if ($paramType && $paramType instanceof \ReflectionNamedType) {
                                $className = $paramType->getName();
                                if (class_exists($className)) {
                                    $refEntity = $this->entityManager->getRepository($className)->find($refId);
                                    if ($refEntity) {
                                        $entity->$setter($refEntity);
                                    }
                                }
                            }
                        }
                    } catch (\Exception $e) {
                        // Skip if IRI resolution fails
                        continue;
                    }
                }
            }
        }
    }
}
