<?php

declare(strict_types=1);

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Entity\Competitor;
use App\Dto\CompetitorInputDto;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Uid\Uuid;
use App\Entity\Organization;
use App\Entity\Deal;

/**
 * Competitor State Processor
 *
 * Handles Input DTO -> Entity transformation for POST, PUT, PATCH operations
 * with support for nested object creation and updates.
 *
 * This file is ALWAYS regenerated. DO NOT edit.
 * For custom processing logic, use Event Subscribers.
 *
 * @generated by Genmax Code Generator
 */
class CompetitorProcessor implements ProcessorInterface
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        #[Autowire(service: 'App\MultiTenant\TenantEntityProcessor')]
        private readonly ProcessorInterface $persistProcessor
    ) {}

    /**
     * @param CompetitorInputDto $data
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): Competitor
    {
        if (!$data instanceof CompetitorInputDto) {
            throw new BadRequestHttpException('Invalid input data type');
        }

        // Determine if this is a create or update operation
        $entity = null;
        $isUpdate = isset($uriVariables['id']);
        $isPatch = $operation->getMethod() === 'PATCH';

        if ($isUpdate) {
            $entity = $this->entityManager->getRepository(Competitor::class)->find($uriVariables['id']);
            if (!$entity) {
                throw new BadRequestHttpException('Competitor not found');
            }
        }

        if (!$entity) {
            $entity = new Competitor();
        }

        // Get original request data to check which fields were actually sent (for PATCH)
        $requestData = $context['request']->toArray() ?? [];

        // Map scalar properties from DTO to Entity
        // name
        if (!$isPatch || array_key_exists('name', $requestData)) {
            $entity->setName($data->name);
        }
        // description
        if (!$isPatch || array_key_exists('description', $requestData)) {
            $entity->setDescription($data->description);
        }
        // industry
        if (!$isPatch || array_key_exists('industry', $requestData)) {
            $entity->setIndustry($data->industry);
        }
        // targetMarket
        if (!$isPatch || array_key_exists('targetMarket', $requestData)) {
            $entity->setTargetmarket($data->targetMarket);
        }
        // foundedYear
        if (!$isPatch || array_key_exists('foundedYear', $requestData)) {
            $entity->setFoundedyear($data->foundedYear);
        }
        // website
        if (!$isPatch || array_key_exists('website', $requestData)) {
            $entity->setWebsite($data->website);
        }
        // active
        if (!$isPatch || array_key_exists('active', $requestData)) {
            $entity->setActive($data->active);
        }
        // marketPosition
        if (!$isPatch || array_key_exists('marketPosition', $requestData)) {
            $entity->setMarketposition($data->marketPosition);
        }
        // strengths
        if (!$isPatch || array_key_exists('strengths', $requestData)) {
            $entity->setStrengths($data->strengths);
        }
        // products
        if (!$isPatch || array_key_exists('products', $requestData)) {
            $entity->setProducts($data->products);
        }
        // weaknesses
        if (!$isPatch || array_key_exists('weaknesses', $requestData)) {
            $entity->setWeaknesses($data->weaknesses);
        }
        // revenue
        if (!$isPatch || array_key_exists('revenue', $requestData)) {
            $entity->setRevenue($data->revenue);
        }
        // employeeCount
        if (!$isPatch || array_key_exists('employeeCount', $requestData)) {
            $entity->setEmployeecount($data->employeeCount);
        }
        // winRate
        if (!$isPatch || array_key_exists('winRate', $requestData)) {
            $entity->setWinrate($data->winRate);
        }
        // lossRate
        if (!$isPatch || array_key_exists('lossRate', $requestData)) {
            $entity->setLossrate($data->lossRate);
        }
        // pricingModel
        if (!$isPatch || array_key_exists('pricingModel', $requestData)) {
            $entity->setPricingmodel($data->pricingModel);
        }
        // headquarters
        if (!$isPatch || array_key_exists('headquarters', $requestData)) {
            $entity->setHeadquarters($data->headquarters);
        }
        // opportunities
        if (!$isPatch || array_key_exists('opportunities', $requestData)) {
            $entity->setOpportunities($data->opportunities);
        }
        // threats
        if (!$isPatch || array_key_exists('threats', $requestData)) {
            $entity->setThreats($data->threats);
        }
        // notes
        if (!$isPatch || array_key_exists('notes', $requestData)) {
            $entity->setNotes($data->notes);
        }
        // lastAnalyzedAt
        if (!$isPatch || array_key_exists('lastAnalyzedAt', $requestData)) {
            $entity->setLastanalyzedat($data->lastAnalyzedAt);
        }
        // keyDifferentiators
        if (!$isPatch || array_key_exists('keyDifferentiators', $requestData)) {
            $entity->setKeydifferentiators($data->keyDifferentiators);
        }

        // Map relationship properties
        // organization: ManyToOne
        // organization is auto-assigned by TenantEntityProcessor if not provided
        if (!$isPatch || array_key_exists('organization', $requestData)) {
            if ($data->organization !== null) {
                if (is_string($data->organization)) {
                    // IRI format: "/api/organizations/{id}"
                    $organizationId = $this->extractIdFromIri($data->organization);
                    $organization = $this->entityManager->getRepository(Organization::class)->find($organizationId);
                    if (!$organization) {
                        throw new BadRequestHttpException('Organization not found: ' . $organizationId);
                    }
                    $entity->setOrganization($organization);
                } else {
                    // Nested object creation (if supported)
                    throw new BadRequestHttpException('Nested organization creation not supported. Use IRI format.');
                }
            }
        }

        // Persist and flush
        return $this->persistProcessor->process($entity, $operation, $uriVariables, $context);
    }

    /**
     * Extract UUID from IRI format
     */
    private function extractIdFromIri(string $iri): Uuid
    {
        $parts = explode('/', $iri);
        $id = end($parts);

        if (!Uuid::isValid($id)) {
            throw new BadRequestHttpException('Invalid UUID in IRI: ' . $iri);
        }

        return Uuid::fromString($id);
    }

    /**
     * Map array data to entity properties using setters
     *
     * @param array $data Associative array of property => value
     * @param object $entity Target entity instance
     */
    private function mapArrayToEntity(array $data, object $entity): void
    {
        foreach ($data as $property => $value) {
            // Skip special keys like @id, @type, @context
            if (str_starts_with($property, '@')) {
                continue;
            }

            // Convert snake_case to camelCase for setter
            $setter = 'set' . str_replace('_', '', ucwords($property, '_'));

            if (method_exists($entity, $setter)) {
                // Handle different value types
                if ($value instanceof \DateTimeInterface || $value === null || is_scalar($value) || is_array($value)) {
                    $entity->$setter($value);
                } elseif (is_string($value) && str_starts_with($value, '/api/')) {
                    // Handle IRI references - resolve to actual entity
                    try {
                        $refId = $this->extractIdFromIri($value);
                        // Infer entity class from IRI pattern (e.g., /api/users/... -> User)
                        $parts = explode('/', trim($value, '/'));
                        if (count($parts) >= 3) {
                            $resourceName = $parts[1]; // e.g., "users"
                            $className = 'App\Entity\\' . ucfirst(rtrim($resourceName, 's'));
                            if (class_exists($className)) {
                                $refEntity = $this->entityManager->getRepository($className)->find($refId);
                                if ($refEntity) {
                                    $entity->$setter($refEntity);
                                }
                            }
                        }
                    } catch (\Exception $e) {
                        // Skip if IRI resolution fails
                        continue;
                    }
                }
            }
        }
    }
}
