<?php

declare(strict_types=1);

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Entity\Country;
use App\Dto\CountryInputDto;
use App\Service\Utils;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Uid\Uuid;
use App\Entity\HolidayTemplate;

/**
 * Country State Processor
 *
 * Handles Input DTO -> Entity transformation for POST, PUT, PATCH operations
 * with support for nested object creation and updates.
 *
 * This file is ALWAYS regenerated. DO NOT edit.
 * For custom processing logic, use Event Subscribers.
 *
 * @generated by Genmax Code Generator
 */
class CountryProcessor implements ProcessorInterface
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        #[Autowire(service: 'App\MultiTenant\TenantEntityProcessor')]
        private readonly ProcessorInterface $persistProcessor
    ) {}

    /**
     * Normalize property name for matching (removes underscores, lowercase)
     * Uses centralized Utils methods instead of manual string manipulation
     */
    private function normalizePropertyName(string $property): string
    {
        // Convert to camelCase (handles snake_case, etc.) then lowercase
        return strtolower(Utils::toCamelCase($property));
    }

    /**
     * Extract property name from method name (e.g., 'addItem' -> 'item')
     */
    private function extractPropertyFromMethod(string $methodName, string $prefix): string
    {
        // Remove prefix (e.g., 'add', 'set') and convert to lowercase
        return strtolower(substr($methodName, strlen($prefix)));
    }

    /**
     * @param CountryInputDto $data
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): Country
    {
        if (!$data instanceof CountryInputDto) {
            throw new BadRequestHttpException('Invalid input data type');
        }

        // Determine if this is a create or update operation
        $entity = null;
        $isUpdate = isset($uriVariables['id']);
        $isPatch = $operation->getMethod() === 'PATCH';

        if ($isUpdate) {
            $entity = $this->entityManager->getRepository(Country::class)->find($uriVariables['id']);
            if (!$entity) {
                throw new BadRequestHttpException('Country not found');
            }
        }

        if (!$entity) {
            $entity = new Country();
        }

        // Get original request data to check which fields were actually sent (for PATCH)
        $requestData = $context['request']->toArray() ?? [];

        // Map scalar properties from DTO to Entity
        // iso2
        if (!$isPatch || array_key_exists('iso2', $requestData)) {
            $entity->setIso2($data->iso2);
        }
        // name
        if (!$isPatch || array_key_exists('name', $requestData)) {
            $entity->setName($data->name);
        }
        // iso3
        if (!$isPatch || array_key_exists('iso3', $requestData)) {
            $entity->setIso3($data->iso3);
        }
        // numericCode
        if (!$isPatch || array_key_exists('numericCode', $requestData)) {
            $entity->setNumericCode($data->numericCode);
        }
        // currencyCode
        if (!$isPatch || array_key_exists('currencyCode', $requestData)) {
            $entity->setCurrencyCode($data->currencyCode);
        }
        // phoneCode
        if (!$isPatch || array_key_exists('phoneCode', $requestData)) {
            $entity->setPhoneCode($data->phoneCode);
        }
        // continent
        if (!$isPatch || array_key_exists('continent', $requestData)) {
            $entity->setContinent($data->continent);
        }
        // capital
        if (!$isPatch || array_key_exists('capital', $requestData)) {
            $entity->setCapital($data->capital);
        }
        // currencySymbol
        if (!$isPatch || array_key_exists('currencySymbol', $requestData)) {
            $entity->setCurrencySymbol($data->currencySymbol);
        }
        // euMember
        if (!$isPatch || array_key_exists('euMember', $requestData)) {
            $entity->setEuMember($data->euMember);
        }
        // region
        if (!$isPatch || array_key_exists('region', $requestData)) {
            $entity->setRegion($data->region);
        }
        // nativeName
        if (!$isPatch || array_key_exists('nativeName', $requestData)) {
            $entity->setNativeName($data->nativeName);
        }
        // officialName
        if (!$isPatch || array_key_exists('officialName', $requestData)) {
            $entity->setOfficialName($data->officialName);
        }
        // active
        if (!$isPatch || array_key_exists('active', $requestData)) {
            $entity->setActive($data->active);
        }
        // subregion
        if (!$isPatch || array_key_exists('subregion', $requestData)) {
            $entity->setSubregion($data->subregion);
        }
        // latitude
        if (!$isPatch || array_key_exists('latitude', $requestData)) {
            $entity->setLatitude($data->latitude);
        }
        // longitude
        if (!$isPatch || array_key_exists('longitude', $requestData)) {
            $entity->setLongitude($data->longitude);
        }
        // timezones
        if (!$isPatch || array_key_exists('timezones', $requestData)) {
            $entity->setTimezones($data->timezones);
        }
        // languages
        if (!$isPatch || array_key_exists('languages', $requestData)) {
            $entity->setLanguages($data->languages);
        }
        // tld
        if (!$isPatch || array_key_exists('tld', $requestData)) {
            $entity->setTld($data->tld);
        }
        // nationalityName
        if (!$isPatch || array_key_exists('nationalityName', $requestData)) {
            $entity->setNationalityName($data->nationalityName);
        }
        // availableForShipping
        if (!$isPatch || array_key_exists('availableForShipping', $requestData)) {
            $entity->setAvailableForShipping($data->availableForShipping);
        }
        // availableForBilling
        if (!$isPatch || array_key_exists('availableForBilling', $requestData)) {
            $entity->setAvailableForBilling($data->availableForBilling);
        }
        // schengenMember
        if (!$isPatch || array_key_exists('schengenMember', $requestData)) {
            $entity->setSchengenMember($data->schengenMember);
        }
        // oecdMember
        if (!$isPatch || array_key_exists('oecdMember', $requestData)) {
            $entity->setOecdMember($data->oecdMember);
        }
        // dataResidencyRequired
        if (!$isPatch || array_key_exists('dataResidencyRequired', $requestData)) {
            $entity->setDataResidencyRequired($data->dataResidencyRequired);
        }
        // postalCodeFormat
        if (!$isPatch || array_key_exists('postalCodeFormat', $requestData)) {
            $entity->setPostalCodeFormat($data->postalCodeFormat);
        }
        // postalCodeRequired
        if (!$isPatch || array_key_exists('postalCodeRequired', $requestData)) {
            $entity->setPostalCodeRequired($data->postalCodeRequired);
        }
        // addressFormat
        if (!$isPatch || array_key_exists('addressFormat', $requestData)) {
            $entity->setAddressFormat($data->addressFormat);
        }
        // taxIdRequired
        if (!$isPatch || array_key_exists('taxIdRequired', $requestData)) {
            $entity->setTaxIdRequired($data->taxIdRequired);
        }
        // population
        if (!$isPatch || array_key_exists('population', $requestData)) {
            $entity->setPopulation($data->population);
        }
        // area
        if (!$isPatch || array_key_exists('area', $requestData)) {
            $entity->setArea($data->area);
        }
        // unMemberSince
        if (!$isPatch || array_key_exists('unMemberSince', $requestData)) {
            $entity->setUnMemberSince($data->unMemberSince);
        }
        // flagEmoji
        if (!$isPatch || array_key_exists('flagEmoji', $requestData)) {
            $entity->setFlagEmoji($data->flagEmoji);
        }
        // flagSvgUrl
        if (!$isPatch || array_key_exists('flagSvgUrl', $requestData)) {
            $entity->setFlagSvgUrl($data->flagSvgUrl);
        }

        // Map relationship properties
        // Persist and flush
        return $this->persistProcessor->process($entity, $operation, $uriVariables, $context);
    }

    /**
     * Extract UUID from IRI format
     */
    private function extractIdFromIri(string $iri): Uuid
    {
        $parts = explode('/', $iri);
        $id = end($parts);

        if (!Uuid::isValid($id)) {
            throw new BadRequestHttpException('Invalid UUID in IRI: ' . $iri);
        }

        return Uuid::fromString($id);
    }

    /**
     * Map array data to entity properties using setters
     * Handles nested collections recursively
     *
     * @param array $data Associative array of property => value
     * @param object $entity Target entity instance
     */
    private function mapArrayToEntity(array $data, object $entity): void
    {
        foreach ($data as $property => $value) {
            // Skip special keys like @id, @type, @context
            if (str_starts_with($property, '@')) {
                continue;
            }

            // Handle nested collections using reflection to find adder methods
            if (is_array($value) && !empty($value) && isset($value[0]) && is_array($value[0])) {
                // Find adder method using reflection - scan all methods starting with 'add'
                $reflectionClass = new \ReflectionClass($entity);
                foreach ($reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC) as $method) {
                    if (!str_starts_with($method->getName(), 'add')) {
                        continue;
                    }

                    // Check if this might be the right adder based on property name similarity
                    $normalizedProperty = $this->normalizePropertyName($property);
                    $extractedFromMethod = $this->extractPropertyFromMethod($method->getName(), 'add');

                    // Try to match: property name should be similar to method's entity name
                    // e.g., 'items' matches 'addItem', 'user_items' matches 'addUserItem'
                    if (!str_contains($normalizedProperty, $extractedFromMethod) &&
                        !str_contains($extractedFromMethod, $normalizedProperty)) {
                        continue;
                    }

                    $parameters = $method->getParameters();
                    if (count($parameters) > 0) {
                        $paramType = $parameters[0]->getType();
                        if ($paramType && $paramType instanceof \ReflectionNamedType) {
                            $className = $paramType->getName();
                            if (class_exists($className)) {
                                $addMethod = $method->getName();
                                $setParentMethods = array_filter(
                                    $reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC),
                                    fn($m) => str_starts_with($m->getName(), 'set')
                                );

                                foreach ($value as $itemData) {
                                    $item = new $className();
                                    $this->mapArrayToEntity($itemData, $item);

                                    // Try to set parent relationship using reflection
                                    $itemReflection = new \ReflectionClass($item);
                                    foreach ($itemReflection->getMethods(\ReflectionMethod::IS_PUBLIC) as $itemMethod) {
                                        if (str_starts_with($itemMethod->getName(), 'set')) {
                                            $params = $itemMethod->getParameters();
                                            if (count($params) > 0) {
                                                $paramType = $params[0]->getType();
                                                if ($paramType instanceof \ReflectionNamedType &&
                                                    $paramType->getName() === get_class($entity)) {
                                                    $item->{$itemMethod->getName()}($entity);
                                                    break;
                                                }
                                            }
                                        }
                                    }

                                    $entity->$addMethod($item);
                                    $this->entityManager->persist($item);
                                }
                                continue 2; // Skip to next property
                            }
                        }
                    }
                }
            }

            // Find setter method using reflection - no string manipulation guessing
            $reflectionClass = new \ReflectionClass($entity);
            $setter = null;
            foreach ($reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC) as $method) {
                if (!str_starts_with($method->getName(), 'set')) {
                    continue;
                }

                // Check if method name matches property (case-insensitive, normalized matching)
                $extractedFromMethod = $this->extractPropertyFromMethod($method->getName(), 'set');
                $normalizedProperty = $this->normalizePropertyName($property);

                if ($extractedFromMethod === $normalizedProperty) {
                    $setter = $method->getName();
                    break;
                }
            }

            if (method_exists($entity, $setter)) {
                // Handle different value types
                if ($value instanceof \DateTimeInterface || $value === null || is_scalar($value)) {
                    $entity->$setter($value);
                } elseif (is_array($value) && !empty($value)) {
                    // Handle JSON arrays (like metadata, tags) - not entity collections
                    $entity->$setter($value);
                } elseif (is_string($value) && str_starts_with($value, '/api/') && $setter) {
                    // Handle IRI references - use reflection to determine expected type
                    try {
                        $refId = $this->extractIdFromIri($value);

                        // Use reflection to get the expected parameter type for the setter
                        $reflectionMethod = new \ReflectionMethod($entity, $setter);
                        $parameters = $reflectionMethod->getParameters();

                        if (count($parameters) > 0) {
                            $paramType = $parameters[0]->getType();
                            if ($paramType && $paramType instanceof \ReflectionNamedType) {
                                $className = $paramType->getName();
                                if (class_exists($className)) {
                                    $refEntity = $this->entityManager->getRepository($className)->find($refId);
                                    if ($refEntity) {
                                        $entity->$setter($refEntity);
                                    }
                                }
                            }
                        }
                    } catch (\Exception $e) {
                        // Skip if IRI resolution fails
                        continue;
                    }
                }
            }
        }
    }
}
