<?php

declare(strict_types=1);

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Entity\EventResourceBooking;
use App\Dto\EventResourceBookingInputDto;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Uid\Uuid;
use App\Entity\Organization;
use App\Entity\User;
use App\Entity\Event;
use App\Entity\EventResource;

/**
 * EventResourceBooking State Processor
 *
 * Handles Input DTO -> Entity transformation for POST, PUT, PATCH operations
 * with support for nested object creation and updates.
 *
 * This file is ALWAYS regenerated. DO NOT edit.
 * For custom processing logic, use Event Subscribers.
 *
 * @generated by Genmax Code Generator
 */
class EventResourceBookingProcessor implements ProcessorInterface
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        #[Autowire(service: 'App\MultiTenant\TenantEntityProcessor')]
        private readonly ProcessorInterface $persistProcessor
    ) {}

    /**
     * @param EventResourceBookingInputDto $data
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): EventResourceBooking
    {
        if (!$data instanceof EventResourceBookingInputDto) {
            throw new BadRequestHttpException('Invalid input data type');
        }

        // Determine if this is a create or update operation
        $entity = null;
        if (isset($uriVariables['id'])) {
            $entity = $this->entityManager->getRepository(EventResourceBooking::class)->find($uriVariables['id']);
            if (!$entity) {
                throw new BadRequestHttpException('EventResourceBooking not found');
            }
        }

        if (!$entity) {
            $entity = new EventResourceBooking();
        }

        // Map scalar properties from DTO to Entity
        $entity->setStarttime($data->startTime);
        $entity->setEndtime($data->endTime);
        $entity->setConfirmed($data->confirmed);
        $entity->setCancelled($data->cancelled);
        $entity->setPaid($data->paid);
        $entity->setDepositamount($data->depositAmount);
        $entity->setTotalamount($data->totalAmount);
        $entity->setConfirmedat($data->confirmedAt);
        $entity->setCancelledat($data->cancelledAt);
        $entity->setCancellationreason($data->cancellationReason);
        $entity->setRemindersent($data->reminderSent);
        $entity->setNotes($data->notes);
        $entity->setQuantity($data->quantity);
        $entity->setStatus($data->status);

        // Map relationship properties
        // organization: ManyToOne
        if ($data->organization !== null) {
            if (is_string($data->organization)) {
                // IRI format: "/api/organizations/{id}"
                $organizationId = $this->extractIdFromIri($data->organization);
                $organization = $this->entityManager->getRepository(Organization::class)->find($organizationId);
                if (!$organization) {
                    throw new BadRequestHttpException('Organization not found: ' . $organizationId);
                }
                $entity->setOrganization($organization);
            } else {
                // Nested object creation (if supported)
                throw new BadRequestHttpException('Nested organization creation not supported. Use IRI format.');
            }
        } else {
            throw new BadRequestHttpException('organization is required');
        }

        // bookedBy: ManyToOne
        if ($data->bookedBy !== null) {
            if (is_string($data->bookedBy)) {
                // IRI format: "/api/users/{id}"
                $bookedById = $this->extractIdFromIri($data->bookedBy);
                $bookedBy = $this->entityManager->getRepository(User::class)->find($bookedById);
                if (!$bookedBy) {
                    throw new BadRequestHttpException('User not found: ' . $bookedById);
                }
                $entity->setBookedby($bookedBy);
            } else {
                // Nested object creation (if supported)
                throw new BadRequestHttpException('Nested bookedBy creation not supported. Use IRI format.');
            }
        }

        // event: ManyToOne
        if ($data->event !== null) {
            if (is_string($data->event)) {
                // IRI format: "/api/events/{id}"
                $eventId = $this->extractIdFromIri($data->event);
                $event = $this->entityManager->getRepository(Event::class)->find($eventId);
                if (!$event) {
                    throw new BadRequestHttpException('Event not found: ' . $eventId);
                }
                $entity->setEvent($event);
            } else {
                // Nested object creation (if supported)
                throw new BadRequestHttpException('Nested event creation not supported. Use IRI format.');
            }
        }

        // resource: ManyToOne
        if ($data->resource !== null) {
            if (is_string($data->resource)) {
                // IRI format: "/api/eventresources/{id}"
                $resourceId = $this->extractIdFromIri($data->resource);
                $resource = $this->entityManager->getRepository(EventResource::class)->find($resourceId);
                if (!$resource) {
                    throw new BadRequestHttpException('EventResource not found: ' . $resourceId);
                }
                $entity->setResource($resource);
            } else {
                // Nested object creation (if supported)
                throw new BadRequestHttpException('Nested resource creation not supported. Use IRI format.');
            }
        }

        // Persist and flush
        return $this->persistProcessor->process($entity, $operation, $uriVariables, $context);
    }

    /**
     * Extract UUID from IRI format
     */
    private function extractIdFromIri(string $iri): Uuid
    {
        $parts = explode('/', $iri);
        $id = end($parts);

        if (!Uuid::isValid($id)) {
            throw new BadRequestHttpException('Invalid UUID in IRI: ' . $iri);
        }

        return Uuid::fromString($id);
    }

}
