<?php

declare(strict_types=1);

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Entity\HolidayTemplate;
use App\Dto\HolidayTemplateInputDto;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Uid\Uuid;
use App\Entity\City;
use App\Entity\Country;

/**
 * HolidayTemplate State Processor
 *
 * Handles Input DTO -> Entity transformation for POST, PUT, PATCH operations
 * with support for nested object creation and updates.
 *
 * This file is ALWAYS regenerated. DO NOT edit.
 * For custom processing logic, use Event Subscribers.
 *
 * @generated by Genmax Code Generator
 */
class HolidayTemplateProcessor implements ProcessorInterface
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        #[Autowire(service: 'App\MultiTenant\TenantEntityProcessor')]
        private readonly ProcessorInterface $persistProcessor
    ) {}

    /**
     * @param HolidayTemplateInputDto $data
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): HolidayTemplate
    {
        if (!$data instanceof HolidayTemplateInputDto) {
            throw new BadRequestHttpException('Invalid input data type');
        }

        // Determine if this is a create or update operation
        $entity = null;
        if (isset($uriVariables['id'])) {
            $entity = $this->entityManager->getRepository(HolidayTemplate::class)->find($uriVariables['id']);
            if (!$entity) {
                throw new BadRequestHttpException('HolidayTemplate not found');
            }
        }

        if (!$entity) {
            $entity = new HolidayTemplate();
        }

        // Map scalar properties from DTO to Entity
        $entity->setName($data->name);
        $entity->setBlocksscheduling($data->blocksScheduling);
        $entity->setRecurrencefrequency($data->recurrenceFrequency);
        $entity->setRecurrenceinterval($data->recurrenceInterval);
        $entity->setSentat($data->sentAt);

        // Map relationship properties
        // city: ManyToOne
        if ($data->city !== null) {
            if (is_string($data->city)) {
                // IRI format: "/api/citys/{id}"
                $cityId = $this->extractIdFromIri($data->city);
                $city = $this->entityManager->getRepository(City::class)->find($cityId);
                if (!$city) {
                    throw new BadRequestHttpException('City not found: ' . $cityId);
                }
                $entity->setCity($city);
            } else {
                // Nested object creation (if supported)
                throw new BadRequestHttpException('Nested city creation not supported. Use IRI format.');
            }
        }

        // country: ManyToOne
        if ($data->country !== null) {
            if (is_string($data->country)) {
                // IRI format: "/api/countrys/{id}"
                $countryId = $this->extractIdFromIri($data->country);
                $country = $this->entityManager->getRepository(Country::class)->find($countryId);
                if (!$country) {
                    throw new BadRequestHttpException('Country not found: ' . $countryId);
                }
                $entity->setCountry($country);
            } else {
                // Nested object creation (if supported)
                throw new BadRequestHttpException('Nested country creation not supported. Use IRI format.');
            }
        }

        // Persist and flush
        return $this->persistProcessor->process($entity, $operation, $uriVariables, $context);
    }

    /**
     * Extract UUID from IRI format
     */
    private function extractIdFromIri(string $iri): Uuid
    {
        $parts = explode('/', $iri);
        $id = end($parts);

        if (!Uuid::isValid($id)) {
            throw new BadRequestHttpException('Invalid UUID in IRI: ' . $iri);
        }

        return Uuid::fromString($id);
    }

}
