<?php

declare(strict_types=1);

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Entity\Organization;
use App\Dto\OrganizationInputDto;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Uid\Uuid;
use App\Entity\StudentCourse;
use App\Entity\Agent;
use App\Entity\Product;
use App\Entity\BillingFrequency;
use App\Entity\Brand;
use App\Entity\Calendar;
use App\Entity\Campaign;
use App\Entity\PipelineStageTemplate;
use App\Entity\TaskTemplate;
use App\Entity\Reminder;
use App\Entity\PipelineTemplate;
use App\Entity\WinReason;
use App\Entity\TreeFlow;
use App\Entity\City;
use App\Entity\CalendarType;
use App\Entity\Attachment;
use App\Entity\DealCategory;
use App\Entity\DealType;
use App\Entity\EventAttendee;
use App\Entity\LostReason;
use App\Entity\MeetingData;
use App\Entity\Notification;
use App\Entity\Company;
use App\Entity\Competitor;
use App\Entity\Contact;
use App\Entity\Course;
use App\Entity\DealStage;
use App\Entity\Deal;
use App\Entity\EventCategory;
use App\Entity\EventResourceBooking;
use App\Entity\EventResourceType;
use App\Entity\EventResource;
use App\Entity\Event;
use App\Entity\Flag;
use App\Entity\Holiday;
use App\Entity\LeadSource;
use App\Entity\Module;
use App\Entity\NotificationType;
use App\Entity\PipelineStage;
use App\Entity\Pipeline;
use App\Entity\ProductBatch;
use App\Entity\ProductCategory;
use App\Entity\ProductLine;
use App\Entity\Profile;
use App\Entity\SocialMedia;
use App\Entity\Tag;
use App\Entity\TalkMessage;
use App\Entity\TalkType;
use App\Entity\Talk;
use App\Entity\TaskType;
use App\Entity\Task;
use App\Entity\TaxCategory;
use App\Entity\User;
use App\Entity\WorkingHour;

/**
 * Organization State Processor
 *
 * Handles Input DTO -> Entity transformation for POST, PUT, PATCH operations
 * with support for nested object creation and updates.
 *
 * This file is ALWAYS regenerated. DO NOT edit.
 * For custom processing logic, use Event Subscribers.
 *
 * @generated by Genmax Code Generator
 */
class OrganizationProcessor implements ProcessorInterface
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        #[Autowire(service: 'App\MultiTenant\TenantEntityProcessor')]
        private readonly ProcessorInterface $persistProcessor
    ) {}

    /**
     * @param OrganizationInputDto $data
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): Organization
    {
        if (!$data instanceof OrganizationInputDto) {
            throw new BadRequestHttpException('Invalid input data type');
        }

        // Determine if this is a create or update operation
        $entity = null;
        if (isset($uriVariables['id'])) {
            $entity = $this->entityManager->getRepository(Organization::class)->find($uriVariables['id']);
            if (!$entity) {
                throw new BadRequestHttpException('Organization not found');
            }
        }

        if (!$entity) {
            $entity = new Organization();
        }

        // Map scalar properties from DTO to Entity
        $entity->setLogopath($data->logoPath);
        $entity->setName($data->name);
        $entity->setLogopathdark($data->logoPathDark);
        $entity->setDescription($data->description);
        $entity->setLogourl($data->logoUrl);
        $entity->setIndustry($data->industry);
        $entity->setAddress($data->address);
        $entity->setWebsite($data->website);
        $entity->setActive($data->active);
        $entity->setBranding($data->branding);
        $entity->setBusinessphone($data->businessPhone);
        $entity->setBusinesssettings($data->businessSettings);
        $entity->setCelphone($data->celPhone);
        $entity->setCompanysize($data->companySize);
        $entity->setContactname($data->contactName);
        $entity->setCurrency($data->currency);
        $entity->setFeatureflags($data->featureFlags);
        $entity->setGeo($data->geo);
        $entity->setIntegrationconfig($data->integrationConfig);
        $entity->setNavconfig($data->navConfig);
        $entity->setPostalcode($data->postalCode);
        $entity->setSecurityconfig($data->securityConfig);
        $entity->setSlug($data->slug);
        $entity->setStatus($data->status);
        $entity->setTimezone($data->timeZone);
        $entity->setUipreferences($data->uiPreferences);

        // Map relationship properties
        // city: ManyToOne
        if ($data->city !== null) {
            if (is_string($data->city)) {
                // IRI format: "/api/citys/{id}"
                $cityId = $this->extractIdFromIri($data->city);
                $city = $this->entityManager->getRepository(City::class)->find($cityId);
                if (!$city) {
                    throw new BadRequestHttpException('City not found: ' . $cityId);
                }
                $entity->setCity($city);
            } else {
                // Nested object creation (if supported)
                throw new BadRequestHttpException('Nested city creation not supported. Use IRI format.');
            }
        }

        // Persist and flush
        return $this->persistProcessor->process($entity, $operation, $uriVariables, $context);
    }

    /**
     * Extract UUID from IRI format
     */
    private function extractIdFromIri(string $iri): Uuid
    {
        $parts = explode('/', $iri);
        $id = end($parts);

        if (!Uuid::isValid($id)) {
            throw new BadRequestHttpException('Invalid UUID in IRI: ' . $iri);
        }

        return Uuid::fromString($id);
    }

}
