<?php

declare(strict_types=1);

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Entity\Organization;
use App\Dto\OrganizationInputDto;
use App\Service\Utils;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Uid\Uuid;
use App\Entity\StudentCourse;
use App\Entity\Agent;
use App\Entity\Product;
use App\Entity\BillingFrequency;
use App\Entity\Brand;
use App\Entity\Calendar;
use App\Entity\Campaign;
use App\Entity\TreeFlow;
use App\Entity\Attachment;
use App\Entity\City;
use App\Entity\CalendarType;
use App\Entity\WinReason;
use App\Entity\PipelineTemplate;
use App\Entity\Reminder;
use App\Entity\TaskTemplate;
use App\Entity\DealCategory;
use App\Entity\DealType;
use App\Entity\EventAttendee;
use App\Entity\LostReason;
use App\Entity\MeetingData;
use App\Entity\Notification;
use App\Entity\PipelineStageTemplate;
use App\Entity\Company;
use App\Entity\Competitor;
use App\Entity\Contact;
use App\Entity\Course;
use App\Entity\DealStage;
use App\Entity\Deal;
use App\Entity\EventCategory;
use App\Entity\EventResourceBooking;
use App\Entity\EventResourceType;
use App\Entity\EventResource;
use App\Entity\Event;
use App\Entity\Flag;
use App\Entity\Holiday;
use App\Entity\LeadSource;
use App\Entity\Module;
use App\Entity\NotificationType;
use App\Entity\PipelineStage;
use App\Entity\Pipeline;
use App\Entity\ProductBatch;
use App\Entity\ProductCategory;
use App\Entity\ProductLine;
use App\Entity\Profile;
use App\Entity\SocialMedia;
use App\Entity\Tag;
use App\Entity\TalkMessage;
use App\Entity\TalkType;
use App\Entity\Talk;
use App\Entity\TaskType;
use App\Entity\Task;
use App\Entity\TaxCategory;
use App\Entity\User;
use App\Entity\WorkingHour;

/**
 * Organization State Processor
 *
 * Handles Input DTO -> Entity transformation for POST, PUT, PATCH operations
 * with support for nested object creation and updates.
 *
 * This file is ALWAYS regenerated. DO NOT edit.
 * For custom processing logic, use Event Subscribers.
 *
 * @generated by Genmax Code Generator
 */
class OrganizationProcessor implements ProcessorInterface
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        #[Autowire(service: 'App\MultiTenant\TenantEntityProcessor')]
        private readonly ProcessorInterface $persistProcessor
    ) {}

    /**
     * Normalize property name for matching (removes underscores, lowercase)
     * Uses centralized Utils methods instead of manual string manipulation
     */
    private function normalizePropertyName(string $property): string
    {
        // Convert to camelCase (handles snake_case, etc.) then lowercase
        return strtolower(Utils::toCamelCase($property));
    }

    /**
     * Extract property name from method name (e.g., 'addItem' -> 'item')
     */
    private function extractPropertyFromMethod(string $methodName, string $prefix): string
    {
        // Remove prefix (e.g., 'add', 'set') and convert to lowercase
        return strtolower(substr($methodName, strlen($prefix)));
    }

    /**
     * @param OrganizationInputDto $data
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): Organization
    {
        if (!$data instanceof OrganizationInputDto) {
            throw new BadRequestHttpException('Invalid input data type');
        }

        // Determine if this is a create or update operation
        $entity = null;
        $isUpdate = isset($uriVariables['id']);
        $isPatch = $operation->getMethod() === 'PATCH';

        if ($isUpdate) {
            $entity = $this->entityManager->getRepository(Organization::class)->find($uriVariables['id']);
            if (!$entity) {
                throw new BadRequestHttpException('Organization not found');
            }
        }

        if (!$entity) {
            $entity = new Organization();
        }

        // Get original request data to check which fields were actually sent (for PATCH)
        $requestData = $context['request']->toArray() ?? [];

        // Map scalar properties from DTO to Entity
        // name
        if (!$isPatch || array_key_exists('name', $requestData)) {
            $entity->setName($data->name);
        }
        // logoPath
        if (!$isPatch || array_key_exists('logoPath', $requestData)) {
            $entity->setLogoPath($data->logoPath);
        }
        // logoPathDark
        if (!$isPatch || array_key_exists('logoPathDark', $requestData)) {
            $entity->setLogoPathDark($data->logoPathDark);
        }
        // description
        if (!$isPatch || array_key_exists('description', $requestData)) {
            $entity->setDescription($data->description);
        }
        // logoUrl
        if (!$isPatch || array_key_exists('logoUrl', $requestData)) {
            $entity->setLogoUrl($data->logoUrl);
        }
        // industry
        if (!$isPatch || array_key_exists('industry', $requestData)) {
            $entity->setIndustry($data->industry);
        }
        // address
        if (!$isPatch || array_key_exists('address', $requestData)) {
            $entity->setAddress($data->address);
        }
        // website
        if (!$isPatch || array_key_exists('website', $requestData)) {
            $entity->setWebsite($data->website);
        }
        // active
        if (!$isPatch || array_key_exists('active', $requestData)) {
            $entity->setActive($data->active);
        }
        // branding
        if (!$isPatch || array_key_exists('branding', $requestData)) {
            $entity->setBranding($data->branding);
        }
        // businessPhone
        if (!$isPatch || array_key_exists('businessPhone', $requestData)) {
            $entity->setBusinessPhone($data->businessPhone);
        }
        // businessSettings
        if (!$isPatch || array_key_exists('businessSettings', $requestData)) {
            $entity->setBusinessSettings($data->businessSettings);
        }
        // celPhone
        if (!$isPatch || array_key_exists('celPhone', $requestData)) {
            $entity->setCelPhone($data->celPhone);
        }
        // companySize
        if (!$isPatch || array_key_exists('companySize', $requestData)) {
            $entity->setCompanySize($data->companySize);
        }
        // contactName
        if (!$isPatch || array_key_exists('contactName', $requestData)) {
            $entity->setContactName($data->contactName);
        }
        // currency
        if (!$isPatch || array_key_exists('currency', $requestData)) {
            $entity->setCurrency($data->currency);
        }
        // featureFlags
        if (!$isPatch || array_key_exists('featureFlags', $requestData)) {
            $entity->setFeatureFlags($data->featureFlags);
        }
        // geo
        if (!$isPatch || array_key_exists('geo', $requestData)) {
            $entity->setGeo($data->geo);
        }
        // integrationConfig
        if (!$isPatch || array_key_exists('integrationConfig', $requestData)) {
            $entity->setIntegrationConfig($data->integrationConfig);
        }
        // navConfig
        if (!$isPatch || array_key_exists('navConfig', $requestData)) {
            $entity->setNavConfig($data->navConfig);
        }
        // postalCode
        if (!$isPatch || array_key_exists('postalCode', $requestData)) {
            $entity->setPostalCode($data->postalCode);
        }
        // securityConfig
        if (!$isPatch || array_key_exists('securityConfig', $requestData)) {
            $entity->setSecurityConfig($data->securityConfig);
        }
        // slug
        if (!$isPatch || array_key_exists('slug', $requestData)) {
            $entity->setSlug($data->slug);
        }
        // status
        if (!$isPatch || array_key_exists('status', $requestData)) {
            $entity->setStatus($data->status);
        }
        // timeZone
        if (!$isPatch || array_key_exists('timeZone', $requestData)) {
            $entity->setTimeZone($data->timeZone);
        }
        // uiPreferences
        if (!$isPatch || array_key_exists('uiPreferences', $requestData)) {
            $entity->setUiPreferences($data->uiPreferences);
        }

        // Map relationship properties
        // city: ManyToOne
        if (!$isPatch || array_key_exists('city', $requestData)) {
            if ($data->city !== null) {
                if (is_string($data->city)) {
                    // IRI format: "/api/ties/{id}"
                    $cityId = $this->extractIdFromIri($data->city);
                    $city = $this->entityManager->getRepository(City::class)->find($cityId);
                    if (!$city) {
                        throw new BadRequestHttpException('City not found: ' . $cityId);
                    }
                    $entity->setCity($city);
                } else {
                    // Nested object creation (if supported)
                    throw new BadRequestHttpException('Nested city creation not supported. Use IRI format.');
                }
            }
        }

        // Persist and flush
        return $this->persistProcessor->process($entity, $operation, $uriVariables, $context);
    }

    /**
     * Extract UUID from IRI format
     */
    private function extractIdFromIri(string $iri): Uuid
    {
        $parts = explode('/', $iri);
        $id = end($parts);

        if (!Uuid::isValid($id)) {
            throw new BadRequestHttpException('Invalid UUID in IRI: ' . $iri);
        }

        return Uuid::fromString($id);
    }

    /**
     * Map array data to entity properties using setters
     * Handles nested collections recursively
     *
     * @param array $data Associative array of property => value
     * @param object $entity Target entity instance
     */
    private function mapArrayToEntity(array $data, object $entity): void
    {
        foreach ($data as $property => $value) {
            // Skip special keys like @id, @type, @context
            if (str_starts_with($property, '@')) {
                continue;
            }

            // Handle nested collections using reflection to find adder methods
            if (is_array($value) && !empty($value) && isset($value[0]) && is_array($value[0])) {
                // Find adder method using reflection - scan all methods starting with 'add'
                $reflectionClass = new \ReflectionClass($entity);
                foreach ($reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC) as $method) {
                    if (!str_starts_with($method->getName(), 'add')) {
                        continue;
                    }

                    // Check if this might be the right adder based on property name similarity
                    $normalizedProperty = $this->normalizePropertyName($property);
                    $extractedFromMethod = $this->extractPropertyFromMethod($method->getName(), 'add');

                    // Try to match: property name should be similar to method's entity name
                    // e.g., 'items' matches 'addItem', 'user_items' matches 'addUserItem'
                    if (!str_contains($normalizedProperty, $extractedFromMethod) &&
                        !str_contains($extractedFromMethod, $normalizedProperty)) {
                        continue;
                    }

                    $parameters = $method->getParameters();
                    if (count($parameters) > 0) {
                        $paramType = $parameters[0]->getType();
                        if ($paramType && $paramType instanceof \ReflectionNamedType) {
                            $className = $paramType->getName();
                            if (class_exists($className)) {
                                $addMethod = $method->getName();
                                $setParentMethods = array_filter(
                                    $reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC),
                                    fn($m) => str_starts_with($m->getName(), 'set')
                                );

                                foreach ($value as $itemData) {
                                    $item = new $className();
                                    $this->mapArrayToEntity($itemData, $item);

                                    // Try to set parent relationship using reflection
                                    $itemReflection = new \ReflectionClass($item);
                                    foreach ($itemReflection->getMethods(\ReflectionMethod::IS_PUBLIC) as $itemMethod) {
                                        if (str_starts_with($itemMethod->getName(), 'set')) {
                                            $params = $itemMethod->getParameters();
                                            if (count($params) > 0) {
                                                $paramType = $params[0]->getType();
                                                if ($paramType instanceof \ReflectionNamedType &&
                                                    $paramType->getName() === get_class($entity)) {
                                                    $item->{$itemMethod->getName()}($entity);
                                                    break;
                                                }
                                            }
                                        }
                                    }

                                    $entity->$addMethod($item);
                                    $this->entityManager->persist($item);
                                }
                                continue 2; // Skip to next property
                            }
                        }
                    }
                }
            }

            // Find setter method using reflection - no string manipulation guessing
            $reflectionClass = new \ReflectionClass($entity);
            $setter = null;
            foreach ($reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC) as $method) {
                if (!str_starts_with($method->getName(), 'set')) {
                    continue;
                }

                // Check if method name matches property (case-insensitive, normalized matching)
                $extractedFromMethod = $this->extractPropertyFromMethod($method->getName(), 'set');
                $normalizedProperty = $this->normalizePropertyName($property);

                if ($extractedFromMethod === $normalizedProperty) {
                    $setter = $method->getName();
                    break;
                }
            }

            if (method_exists($entity, $setter)) {
                // Handle different value types
                if ($value instanceof \DateTimeInterface || $value === null || is_scalar($value)) {
                    $entity->$setter($value);
                } elseif (is_array($value) && !empty($value)) {
                    // Handle JSON arrays (like metadata, tags) - not entity collections
                    $entity->$setter($value);
                } elseif (is_string($value) && str_starts_with($value, '/api/') && $setter) {
                    // Handle IRI references - use reflection to determine expected type
                    try {
                        $refId = $this->extractIdFromIri($value);

                        // Use reflection to get the expected parameter type for the setter
                        $reflectionMethod = new \ReflectionMethod($entity, $setter);
                        $parameters = $reflectionMethod->getParameters();

                        if (count($parameters) > 0) {
                            $paramType = $parameters[0]->getType();
                            if ($paramType && $paramType instanceof \ReflectionNamedType) {
                                $className = $paramType->getName();
                                if (class_exists($className)) {
                                    $refEntity = $this->entityManager->getRepository($className)->find($refId);
                                    if ($refEntity) {
                                        $entity->$setter($refEntity);
                                    }
                                }
                            }
                        }
                    } catch (\Exception $e) {
                        // Skip if IRI resolution fails
                        continue;
                    }
                }
            }
        }
    }
}
