framework:
    cache:
        # Unique name for cache key namespacing
        prefix_seed: luminai_app

        # Development uses filesystem cache
        app: cache.adapter.filesystem
        system: cache.adapter.system

        # Define specialized cache pools
        pools:
            # Application cache for business logic
            app.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600 # 1 hour

            # API response cache for better performance
            api.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 300 # 5 minutes

            # Long-term cache for rarely changing data
            app.long_term:
                adapter: cache.adapter.filesystem
                default_lifetime: 86400 # 24 hours

when@prod:
    framework:
        cache:
            # Use Redis in production for better performance and clustering
            # SECURITY: Redis now requires authentication (see REDIS_PASSWORD in .env)
            app: cache.adapter.redis
            system: cache.adapter.redis
            default_redis_provider: '%env(REDIS_URL)%'

            pools:
                app.cache:
                    adapter: cache.adapter.redis
                    # Use database 1 for application cache
                    provider: '%env(resolve:REDIS_URL)%/1'
                    default_lifetime: 3600

                api.cache:
                    adapter: cache.adapter.redis
                    # Use database 2 for API cache
                    provider: '%env(resolve:REDIS_URL)%/2'
                    default_lifetime: 300

                app.long_term:
                    adapter: cache.adapter.redis
                    # Use database 3 for long-term cache
                    provider: '%env(resolve:REDIS_URL)%/3'
                    default_lifetime: 86400

when@test:
    framework:
        cache:
            app: cache.adapter.array
            system: cache.adapter.array
            pools:
                app.cache:
                    adapter: cache.adapter.array
                api.cache:
                    adapter: cache.adapter.array
                app.long_term:
                    adapter: cache.adapter.array
