doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_pgsql
        server_version: '18'
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        enable_native_lazy_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false
        dql:
            string_functions:
                unaccent: App\Doctrine\DQL\UnaccentFunction
            numeric_functions:
                extract: App\Doctrine\DQL\ExtractFunction
        filters:
            organization_filter:
                class: App\Doctrine\Filter\OrganizationFilter
                enabled: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            # Enable second-level cache for entity caching
            second_level_cache:
                enabled: true
                log_enabled: false
                region_cache_driver:
                    type: pool
                    pool: doctrine.second_level_cache_pool
                regions:
                    treeflow_region:
                        lifetime: 3600
                        cache_driver:
                            type: pool
                            pool: doctrine.second_level_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
                doctrine.second_level_cache_pool:
                    adapter: cache.adapter.redis
                    provider: '%env(resolve:REDIS_URL)%/4'
                    default_lifetime: 3600
