# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Locale configuration
    enabled_locales: ['en', 'pt_BR']

    # Trust proxy headers for HTTPS detection
    trusted_proxies: '127.0.0.1,::1,nginx'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

    # CSRF protection enabled
    csrf_protection: true

    # Session configuration with security features
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax
        gc_probability: 1
        gc_divisor: 100
        gc_maxlifetime: 3600

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
