monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - app # Application-specific logs
        - performance # Performance monitoring
        - security # Security events
        - business # Business logic events
        - audit # Audit logging for entity changes
        - video_processing # Video processing background jobs

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json

            # Application-specific logs to file with rotation
            app_file:
                type: rotating_file
                path: "%kernel.logs_dir%/app.log"
                level: info
                channels: ['app']
                formatter: monolog.formatter.json
                max_files: 30  # Keep 30 days of logs
                filename_format: '{filename}-{date}'
                date_format: 'Y-m-d'

            # Performance monitoring logs with rotation
            performance_file:
                type: rotating_file
                path: "%kernel.logs_dir%/performance.log"
                level: info
                channels: ['performance']
                formatter: monolog.formatter.json
                max_files: 30  # Keep 30 days of logs
                filename_format: '{filename}-{date}'
                date_format: 'Y-m-d'

            # Security events logging with rotation
            security_file:
                type: rotating_file
                path: "%kernel.logs_dir%/security.log"
                level: warning
                channels: ['security']
                formatter: monolog.formatter.json
                max_files: 365  # Keep 1 year of security logs
                filename_format: '{filename}-{date}'
                date_format: 'Y-m-d'

            # Business logic events with rotation
            business_file:
                type: rotating_file
                path: "%kernel.logs_dir%/business.log"
                level: info
                channels: ['business']
                formatter: monolog.formatter.json
                max_files: 30  # Keep 30 days of logs
                filename_format: '{filename}-{date}'
                date_format: 'Y-m-d'

            # Critical errors to syslog for monitoring systems
            syslog_critical:
                type: syslog
                level: critical
                facility: local0
                ident: luminai_app

            # Audit events logging with rotation
            audit_file:
                type: rotating_file
                path: "%kernel.logs_dir%/audit.log"
                level: info
                channels: ['audit']
                formatter: monolog.formatter.json
                max_files: 90  # Keep 90 days of logs
                filename_format: '{filename}-{date}'
                date_format: 'Y-m-d'

            # Video processing logs with rotation
            video_processing_file:
                type: rotating_file
                path: "%kernel.logs_dir%/video_processing.log"
                level: info
                channels: ['video_processing']
                formatter: monolog.formatter.json
                max_files: 30  # Keep 30 days of logs
                filename_format: '{filename}-{date}'
                date_format: 'Y-m-d'
