# TODO: Install symfony/lock component to enable rate limiting
# Run: composer require symfony/lock

#framework:
#    rate_limiter:
#        # Authentication rate limiting
#        auth_login:
#            policy: 'sliding_window'
#            limit: 5
#            interval: '15 minutes'
#            lock_factory: 'lock.redis.factory'
#
#        auth_register:
#            policy: 'sliding_window'
#            limit: 3
#            interval: '1 hour'
#            lock_factory: 'lock.redis.factory'
#
#        # API rate limiting
#        api_anonymous:
#            policy: 'sliding_window'
#            limit: 100
#            interval: '1 hour'
#            lock_factory: 'lock.redis.factory'
#
#        api_authenticated:
#            policy: 'sliding_window'
#            limit: 1000
#            interval: '1 hour'
#            lock_factory: 'lock.redis.factory'