when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            only_main_requests: true
            collect_serializer_data: true
        router:
            default_uri: 'https://localhost'
when@prod:
    web_profiler:
        toolbar: fale
        intercept_redirects: false

    framework:
        profiler:
            only_main_requests: false
            collect_serializer_data: false
        router:
            default_uri: 'https://avelum.com.br'

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
